#!/usr/bin/env ruby

$:.unshift "."
require "interpreter"
require "readline"

interpreter = Interpreter.new


if file = ARGV.first
  interpreter.eval File.read(file)


else
  puts "Nya nya nyaruko: "
  loop do
    line = Readline::readline(">> ")
    Readline::HISTORY.push(line)
    value = interpreter.eval(line)
    puts "=> #{value.ruby_value.inspect}"
  end
  
end